### ISSUE TITLE
le over sur les bulles ne marche pas

### ISSUE THREAD

**Issue by poulki** [MapleNoise/CCB-Projet#10]
![over](https://cloud.githubusercontent.com/assets/5251850/6479933/dc1fc3e0-c24d-11e4-945b-157572fb0911.png)
On ne peut cliquer sur les images qui apparaisse lorsqu'on fait un over sur les bulles.

**Comment by mathieupetrini** [comment]
Personellement j'ai pu cliquer sur ces bulles. Seulement parfois le temps d'attente du hover est un trop long.

**Comment by mathieupetrini** [comment]
Enfaite je confirme l'issue de Keita. La seule bulle cliquable est à la première à gauche. Les autres impossibles

**Comment by MangelMaxime** [comment]
A vérifier si c'est encore persistant. Il se peut que ce soit lier à la connexion.

**Comment by MapleNoise** [comment]
J'ai des scroll-top automatiques quand j'hover les bulles parfois

**Comment by Heavenlot** [comment]
Corrigé.
Le scroll-top sera traité dans l'issue #33
