### ISSUE TITLE
Filtre sur les produits

### ISSUE THREAD

**Issue by mathieupetrini** [MapleNoise/CCB-Projet#34]
Je clique sur formations sur le schéma de reconversion.
Je coche tout les types, que deux produits sortent. 
Je décoche tout les types, beaucoup plus de produits apparaissent.

Un problème sur les filtres ?

Navigateur : Google Chrome
OS : Mac OS X

**Comment by mathieupetrini** [comment]
Enfaite si je décoche juste bibliothèque beaucoup plus de choses apparaissent.

**Comment by MangelMaxime** [comment]
Piste : Des quizzs sont retournés, il faut vérifier l'attribution des catégories.

Les quizzs font partis des outils.

**Comment by MangelMaxime** [comment]
Les filtres ont été revu et fonctionne correctement maintenant.
