### ISSUE TITLE
Connexion ne fonctionne pas

### ISSUE THREAD

**Issue by mathieupetrini** [MapleNoise/CCB-Projet#37]
Impossible de se connecter.
Aucun feedback pour savoir si je me suis trompé de mot de passe.

Navigateur : Google Chrome
OS : Mac OS X

**Comment by MangelMaxime** [comment]
Il faut ajouter une information concernant l'échec de la connexion.

**Comment by MangelMaxime** [comment]
@ThomasAy , développe depuis la Branche Dev. Elle contient la gestion des status utilisateurs lors de la connexion.
