### ISSUE TITLE
Création chapitre vide impossible

### ISSUE THREAD

**Issue by poulki** [MapleNoise/CCB-Projet#41]
Navigateur : Google Chrome
OS :Windows Seven
Connecté avec coach@gmail.com

Lors de la création d'un chapitre, si ce dernier est vide, on tombe sur une page d'erreur.
![image](https://cloud.githubusercontent.com/assets/5251850/6592558/4c7dd76c-c7d0-11e4-8aaa-440a02532f61.png)

**Comment by MangelMaxime** [comment]
On ne peux pas créer de chapitre vide.
