### ISSUE TITLE
Création produit impossible

### ISSUE THREAD

**Issue by poulki** [MapleNoise/CCB-Projet#42]
Navigateur : Google Chrome
OS :Windows Seven
Connecté avec coach@gmail.com

Création d'un produit, rempli avec les champs suivants.(voir image)
![image](https://cloud.githubusercontent.com/assets/5251850/6592704/7eba5be6-c7d1-11e4-8ea2-658b53c1b5a7.png)

Voici le résultat
![image](https://cloud.githubusercontent.com/assets/5251850/6592728/b18b26ea-c7d1-11e4-87b9-699fe0b065d6.png)
.

**Comment by MangelMaxime** [comment]
Les problèmes présentés ici sont dues à une description trop courte par exemple.

TODO: Feedback, concernant les pré-requis des champs incorrect.
