### ISSUE TITLE
Footer non aligné

### ISSUE THREAD

**Issue by poulki** [MapleNoise/CCB-Projet#43]
Navigateur : Google Chrome
OS :Windows Seven
Connecté avec coach@gmail.com / et non connecté
résolution : 1366*768
Infos : ma barre de tâche est a droite.

![image](https://cloud.githubusercontent.com/assets/5251850/6592783/4f0baa98-c7d2-11e4-8ff0-3dd743d335cc.png)

Les éléments Espace client Témoignages clients Mentions légales C.G.V ne sont pas aligné en bas sur la page d'accueil.

**Comment by Adjunta** [comment]
C'est reglé, sauf que pour de plus basses résolutions, c'est normal que les liens se "chevauchent" de la sorte, cela fait partie du responsive (qui peut être repenser)
