### ISSUE TITLE
Possibilité d'ajouter des lettres pour un prix à une nouvelle formation

### ISSUE THREAD

**Issue by poulki** [MapleNoise/CCB-Projet#48]
Navigateur : Google Chrome
OS :Windows Seven
Connecté avec coach@gmail.com

![image](https://cloud.githubusercontent.com/assets/5251850/6593305/cd8d3a80-c7d7-11e4-9be1-b8183d3d6d06.png)

Il n'y a pas de filtre, je peux par exemple mettre " chocolat"  pour le prix. ET ça valide tout de même l'ajout de la formation.

**Comment by ThomasAy** [comment]
@poulki on ne peut pas _forcer_ l'utilisateur à entrer des nombres, par contre, c'est pas normal que ça valide
